version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run: curl https://install.meteor.com/ | sh
      - checkout
      - run: meteor npm run test
