version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run: sudo apt-get install xvfb
      - run: Xvfb :99 -ac &
      - run: export DISPLAY=:99
      - run: curl https://install.meteor.com/ | sh
      - checkout
      - run: meteor npm i
      - run: meteor npm run test
